/*
 * VRChat API Documentation
 *
 *
 * The version of the OpenAPI document: 1.19.2
 * Contact: vrchatapi.lpv0t@aries.fyi
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = VRChat.API.Client.OpenAPIDateConverter;

namespace VRChat.API.Model
{
    /// <summary>
    /// CurrentUserPlatformHistoryInner
    /// </summary>
    [DataContract(Name = "CurrentUser_platform_history_inner")]
    public partial class CurrentUserPlatformHistoryInner : IEquatable<CurrentUserPlatformHistoryInner>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CurrentUserPlatformHistoryInner" /> class.
        /// </summary>
        /// <param name="isMobile">isMobile.</param>
        /// <param name="platform">platform.</param>
        /// <param name="recorded">recorded.</param>
        public CurrentUserPlatformHistoryInner(bool isMobile = default(bool), string platform = default(string), DateTime recorded = default(DateTime))
        {
            this.IsMobile = isMobile;
            this.Platform = platform;
            this.Recorded = recorded;
        }

        /// <summary>
        /// Gets or Sets IsMobile
        /// </summary>
        [DataMember(Name = "isMobile", EmitDefaultValue = true)]
        public bool IsMobile { get; set; }

        /// <summary>
        /// Gets or Sets Platform
        /// </summary>
        [DataMember(Name = "platform", EmitDefaultValue = true)]
        public string Platform { get; set; }

        /// <summary>
        /// Gets or Sets Recorded
        /// </summary>
        [DataMember(Name = "recorded", EmitDefaultValue = false)]
        public DateTime Recorded { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class CurrentUserPlatformHistoryInner {\n");
            sb.Append("  IsMobile: ").Append(IsMobile).Append("\n");
            sb.Append("  Platform: ").Append(Platform).Append("\n");
            sb.Append("  Recorded: ").Append(Recorded).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as CurrentUserPlatformHistoryInner);
        }

        /// <summary>
        /// Returns true if CurrentUserPlatformHistoryInner instances are equal
        /// </summary>
        /// <param name="input">Instance of CurrentUserPlatformHistoryInner to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(CurrentUserPlatformHistoryInner input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.IsMobile == input.IsMobile ||
                    this.IsMobile.Equals(input.IsMobile)
                ) && 
                (
                    this.Platform == input.Platform ||
                    (this.Platform != null &&
                    this.Platform.Equals(input.Platform))
                ) && 
                (
                    this.Recorded == input.Recorded ||
                    (this.Recorded != null &&
                    this.Recorded.Equals(input.Recorded))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                hashCode = (hashCode * 59) + this.IsMobile.GetHashCode();
                if (this.Platform != null)
                {
                    hashCode = (hashCode * 59) + this.Platform.GetHashCode();
                }
                if (this.Recorded != null)
                {
                    hashCode = (hashCode * 59) + this.Recorded.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        public IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
