/*
 * VRChat API Documentation
 *
 *
 * The version of the OpenAPI document: 1.20.7
 * Contact: vrchatapi.lpv0t@aries.fyi
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = VRChat.API.Client.FileParameter;
using OpenAPIDateConverter = VRChat.API.Client.OpenAPIDateConverter;

namespace VRChat.API.Model
{
    /// <summary>
    /// EconomyPayoutStatus
    /// </summary>
    [DataContract(Name = "EconomyPayoutStatus")]
    public partial class EconomyPayoutStatus : IEquatable<EconomyPayoutStatus>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="EconomyPayoutStatus" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected EconomyPayoutStatus() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="EconomyPayoutStatus" /> class.
        /// </summary>
        /// <param name="accountId">accountId (required).</param>
        /// <param name="activePayout">activePayout.</param>
        /// <param name="activePayoutCancellable">activePayoutCancellable (required).</param>
        /// <param name="activePayoutTiliaAmount">activePayoutTiliaAmount (required).</param>
        /// <param name="earningsBalance">earningsBalance (required).</param>
        /// <param name="eligibility">eligibility (required).</param>
        /// <param name="payoutEligible">payoutEligible (required).</param>
        /// <param name="tiliaId">tiliaId (required).</param>
        public EconomyPayoutStatus(int accountId = default, EconomyPayout activePayout = default, bool activePayoutCancellable = default, int activePayoutTiliaAmount = default, int earningsBalance = default, EconomyPayoutEligibility eligibility = default, bool payoutEligible = default, string tiliaId = default)
        {
            this.AccountId = accountId;
            this.ActivePayoutCancellable = activePayoutCancellable;
            this.ActivePayoutTiliaAmount = activePayoutTiliaAmount;
            this.EarningsBalance = earningsBalance;
            // Allow null values for required properties to handle unexpected API responses gracefully
            this.Eligibility = eligibility;
            this.PayoutEligible = payoutEligible;
            // Allow null values for required properties to handle unexpected API responses gracefully
            this.TiliaId = tiliaId;
            this.ActivePayout = activePayout;
        }

        /// <summary>
        /// Gets or Sets AccountId
        /// </summary>
        [DataMember(Name = "accountId", IsRequired = true, EmitDefaultValue = true)]
        public int AccountId { get; set; }

        /// <summary>
        /// Gets or Sets ActivePayout
        /// </summary>
        [DataMember(Name = "activePayout", EmitDefaultValue = false)]
        public EconomyPayout ActivePayout { get; set; }

        /// <summary>
        /// Gets or Sets ActivePayoutCancellable
        /// </summary>
        [DataMember(Name = "activePayoutCancellable", IsRequired = true, EmitDefaultValue = true)]
        public bool ActivePayoutCancellable { get; set; }

        /// <summary>
        /// Gets or Sets ActivePayoutTiliaAmount
        /// </summary>
        [DataMember(Name = "activePayoutTiliaAmount", IsRequired = true, EmitDefaultValue = true)]
        public int ActivePayoutTiliaAmount { get; set; }

        /// <summary>
        /// Gets or Sets EarningsBalance
        /// </summary>
        [DataMember(Name = "earningsBalance", IsRequired = true, EmitDefaultValue = true)]
        public int EarningsBalance { get; set; }

        /// <summary>
        /// Gets or Sets Eligibility
        /// </summary>
        [DataMember(Name = "eligibility", IsRequired = true, EmitDefaultValue = true)]
        public EconomyPayoutEligibility Eligibility { get; set; }

        /// <summary>
        /// Gets or Sets PayoutEligible
        /// </summary>
        [DataMember(Name = "payoutEligible", IsRequired = true, EmitDefaultValue = true)]
        public bool PayoutEligible { get; set; }

        /// <summary>
        /// Gets or Sets TiliaId
        /// </summary>
        [DataMember(Name = "tiliaId", IsRequired = true, EmitDefaultValue = true)]
        public string TiliaId { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class EconomyPayoutStatus {\n");
            sb.Append("  AccountId: ").Append(AccountId).Append("\n");
            sb.Append("  ActivePayout: ").Append(ActivePayout).Append("\n");
            sb.Append("  ActivePayoutCancellable: ").Append(ActivePayoutCancellable).Append("\n");
            sb.Append("  ActivePayoutTiliaAmount: ").Append(ActivePayoutTiliaAmount).Append("\n");
            sb.Append("  EarningsBalance: ").Append(EarningsBalance).Append("\n");
            sb.Append("  Eligibility: ").Append(Eligibility).Append("\n");
            sb.Append("  PayoutEligible: ").Append(PayoutEligible).Append("\n");
            sb.Append("  TiliaId: ").Append(TiliaId).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as EconomyPayoutStatus);
        }

        /// <summary>
        /// Returns true if EconomyPayoutStatus instances are equal
        /// </summary>
        /// <param name="input">Instance of EconomyPayoutStatus to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(EconomyPayoutStatus input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.AccountId == input.AccountId ||
                    this.AccountId.Equals(input.AccountId)
                ) && 
                (
                    this.ActivePayout == input.ActivePayout ||
                    (this.ActivePayout != null &&
                    this.ActivePayout.Equals(input.ActivePayout))
                ) && 
                (
                    this.ActivePayoutCancellable == input.ActivePayoutCancellable ||
                    this.ActivePayoutCancellable.Equals(input.ActivePayoutCancellable)
                ) && 
                (
                    this.ActivePayoutTiliaAmount == input.ActivePayoutTiliaAmount ||
                    this.ActivePayoutTiliaAmount.Equals(input.ActivePayoutTiliaAmount)
                ) && 
                (
                    this.EarningsBalance == input.EarningsBalance ||
                    this.EarningsBalance.Equals(input.EarningsBalance)
                ) && 
                (
                    this.Eligibility == input.Eligibility ||
                    (this.Eligibility != null &&
                    this.Eligibility.Equals(input.Eligibility))
                ) && 
                (
                    this.PayoutEligible == input.PayoutEligible ||
                    this.PayoutEligible.Equals(input.PayoutEligible)
                ) && 
                (
                    this.TiliaId == input.TiliaId ||
                    (this.TiliaId != null &&
                    this.TiliaId.Equals(input.TiliaId))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                hashCode = (hashCode * 59) + this.AccountId.GetHashCode();
                if (this.ActivePayout != null)
                {
                    hashCode = (hashCode * 59) + this.ActivePayout.GetHashCode();
                }
                hashCode = (hashCode * 59) + this.ActivePayoutCancellable.GetHashCode();
                hashCode = (hashCode * 59) + this.ActivePayoutTiliaAmount.GetHashCode();
                hashCode = (hashCode * 59) + this.EarningsBalance.GetHashCode();
                if (this.Eligibility != null)
                {
                    hashCode = (hashCode * 59) + this.Eligibility.GetHashCode();
                }
                hashCode = (hashCode * 59) + this.PayoutEligible.GetHashCode();
                if (this.TiliaId != null)
                {
                    hashCode = (hashCode * 59) + this.TiliaId.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
