/*
 * VRChat API Documentation
 *
 *
 * The version of the OpenAPI document: 1.20.5
 * Contact: vrchatapi.lpv0t@aries.fyi
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = VRChat.API.Client.FileParameter;
using OpenAPIDateConverter = VRChat.API.Client.OpenAPIDateConverter;

namespace VRChat.API.Model
{
    /// <summary>
    /// GroupMyMember
    /// </summary>
    [DataContract(Name = "GroupMyMember")]
    public partial class GroupMyMember : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="GroupMyMember" /> class.
        /// </summary>
        /// <param name="id">id.</param>
        /// <param name="groupId">groupId.</param>
        /// <param name="userId">A users unique ID, usually in the form of &#x60;usr_c1644b5b-3ca4-45b4-97c6-a2a0de70d469&#x60;. Legacy players can have old IDs in the form of &#x60;8JoV9XEdpo&#x60;. The ID can never be changed..</param>
        /// <param name="roleIds">roleIds.</param>
        /// <param name="acceptedByDisplayName">acceptedByDisplayName.</param>
        /// <param name="acceptedById">acceptedById.</param>
        /// <param name="createdAt">createdAt.</param>
        /// <param name="managerNotes">managerNotes.</param>
        /// <param name="membershipStatus">membershipStatus.</param>
        /// <param name="isSubscribedToAnnouncements">isSubscribedToAnnouncements (default to true).</param>
        /// <param name="isSubscribedToEventAnnouncements">isSubscribedToEventAnnouncements.</param>
        /// <param name="visibility">visibility.</param>
        /// <param name="isRepresenting">isRepresenting (default to false).</param>
        /// <param name="joinedAt">joinedAt.</param>
        /// <param name="bannedAt">bannedAt.</param>
        /// <param name="has2FA">has2FA (default to false).</param>
        /// <param name="hasJoinedFromPurchase">hasJoinedFromPurchase (default to false).</param>
        /// <param name="lastPostReadAt">lastPostReadAt.</param>
        /// <param name="mRoleIds">mRoleIds.</param>
        /// <param name="permissions">permissions.</param>
        public GroupMyMember(string id = default, string groupId = default, string userId = default, List<string> roleIds = default, string acceptedByDisplayName = default, string acceptedById = default, DateTime createdAt = default, string managerNotes = default, string membershipStatus = default, bool isSubscribedToAnnouncements = true, bool isSubscribedToEventAnnouncements = default, string visibility = default, bool isRepresenting = false, DateTime joinedAt = default, string bannedAt = default, bool has2FA = false, bool hasJoinedFromPurchase = false, DateTime? lastPostReadAt = default, List<string> mRoleIds = default, List<GroupPermissions> permissions = default)
        {
            this.Id = id;
            this.GroupId = groupId;
            this.UserId = userId;
            this.RoleIds = roleIds;
            this.AcceptedByDisplayName = acceptedByDisplayName;
            this.AcceptedById = acceptedById;
            this.CreatedAt = createdAt;
            this.ManagerNotes = managerNotes;
            this.MembershipStatus = membershipStatus;
            this.IsSubscribedToAnnouncements = isSubscribedToAnnouncements;
            this.IsSubscribedToEventAnnouncements = isSubscribedToEventAnnouncements;
            this.Visibility = visibility;
            this.IsRepresenting = isRepresenting;
            this.JoinedAt = joinedAt;
            this.BannedAt = bannedAt;
            this.Has2FA = has2FA;
            this.HasJoinedFromPurchase = hasJoinedFromPurchase;
            this.LastPostReadAt = lastPostReadAt;
            this.MRoleIds = mRoleIds;
            this.Permissions = permissions;
        }

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        /*
        <example>gmem_95cdb3b4-4643-4eb6-bdab-46a4e1e5ce37</example>
        */
        [DataMember(Name = "id", EmitDefaultValue = false)]
        public string Id { get; set; }

        /// <summary>
        /// Gets or Sets GroupId
        /// </summary>
        /*
        <example>grp_71a7ff59-112c-4e78-a990-c7cc650776e5</example>
        */
        [DataMember(Name = "groupId", EmitDefaultValue = false)]
        public string GroupId { get; set; }

        /// <summary>
        /// A users unique ID, usually in the form of &#x60;usr_c1644b5b-3ca4-45b4-97c6-a2a0de70d469&#x60;. Legacy players can have old IDs in the form of &#x60;8JoV9XEdpo&#x60;. The ID can never be changed.
        /// </summary>
        /// <value>A users unique ID, usually in the form of &#x60;usr_c1644b5b-3ca4-45b4-97c6-a2a0de70d469&#x60;. Legacy players can have old IDs in the form of &#x60;8JoV9XEdpo&#x60;. The ID can never be changed.</value>
        /*
        <example>usr_c1644b5b-3ca4-45b4-97c6-a2a0de70d469</example>
        */
        [DataMember(Name = "userId", EmitDefaultValue = false)]
        public string UserId { get; set; }

        /// <summary>
        /// Gets or Sets RoleIds
        /// </summary>
        [DataMember(Name = "roleIds", EmitDefaultValue = false)]
        public List<string> RoleIds { get; set; }

        /// <summary>
        /// Gets or Sets AcceptedByDisplayName
        /// </summary>
        [DataMember(Name = "acceptedByDisplayName", EmitDefaultValue = true)]
        public string AcceptedByDisplayName { get; set; }

        /// <summary>
        /// Gets or Sets AcceptedById
        /// </summary>
        [DataMember(Name = "acceptedById", EmitDefaultValue = true)]
        public string AcceptedById { get; set; }

        /// <summary>
        /// Gets or Sets CreatedAt
        /// </summary>
        [DataMember(Name = "createdAt", EmitDefaultValue = false)]
        public DateTime CreatedAt { get; set; }

        /// <summary>
        /// Gets or Sets ManagerNotes
        /// </summary>
        [DataMember(Name = "managerNotes", EmitDefaultValue = false)]
        public string ManagerNotes { get; set; }

        /// <summary>
        /// Gets or Sets MembershipStatus
        /// </summary>
        /*
        <example>member</example>
        */
        [DataMember(Name = "membershipStatus", EmitDefaultValue = false)]
        public string MembershipStatus { get; set; }

        /// <summary>
        /// Gets or Sets IsSubscribedToAnnouncements
        /// </summary>
        [DataMember(Name = "isSubscribedToAnnouncements", EmitDefaultValue = true)]
        public bool IsSubscribedToAnnouncements { get; set; }

        /// <summary>
        /// Gets or Sets IsSubscribedToEventAnnouncements
        /// </summary>
        [DataMember(Name = "isSubscribedToEventAnnouncements", EmitDefaultValue = true)]
        public bool IsSubscribedToEventAnnouncements { get; set; }

        /// <summary>
        /// Gets or Sets Visibility
        /// </summary>
        /*
        <example>visible</example>
        */
        [DataMember(Name = "visibility", EmitDefaultValue = false)]
        public string Visibility { get; set; }

        /// <summary>
        /// Gets or Sets IsRepresenting
        /// </summary>
        [DataMember(Name = "isRepresenting", EmitDefaultValue = true)]
        public bool IsRepresenting { get; set; }

        /// <summary>
        /// Gets or Sets JoinedAt
        /// </summary>
        [DataMember(Name = "joinedAt", EmitDefaultValue = false)]
        public DateTime JoinedAt { get; set; }

        /// <summary>
        /// Gets or Sets BannedAt
        /// </summary>
        [DataMember(Name = "bannedAt", EmitDefaultValue = true)]
        public string BannedAt { get; set; }

        /// <summary>
        /// Gets or Sets Has2FA
        /// </summary>
        [DataMember(Name = "has2FA", EmitDefaultValue = true)]
        public bool Has2FA { get; set; }

        /// <summary>
        /// Gets or Sets HasJoinedFromPurchase
        /// </summary>
        [DataMember(Name = "hasJoinedFromPurchase", EmitDefaultValue = true)]
        public bool HasJoinedFromPurchase { get; set; }

        /// <summary>
        /// Gets or Sets LastPostReadAt
        /// </summary>
        [DataMember(Name = "lastPostReadAt", EmitDefaultValue = true)]
        public DateTime? LastPostReadAt { get; set; }

        /// <summary>
        /// Gets or Sets MRoleIds
        /// </summary>
        [DataMember(Name = "mRoleIds", EmitDefaultValue = false)]
        public List<string> MRoleIds { get; set; }

        /// <summary>
        /// Gets or Sets Permissions
        /// </summary>
        [DataMember(Name = "permissions", EmitDefaultValue = false)]
        public List<GroupPermissions> Permissions { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class GroupMyMember {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  GroupId: ").Append(GroupId).Append("\n");
            sb.Append("  UserId: ").Append(UserId).Append("\n");
            sb.Append("  RoleIds: ").Append(RoleIds).Append("\n");
            sb.Append("  AcceptedByDisplayName: ").Append(AcceptedByDisplayName).Append("\n");
            sb.Append("  AcceptedById: ").Append(AcceptedById).Append("\n");
            sb.Append("  CreatedAt: ").Append(CreatedAt).Append("\n");
            sb.Append("  ManagerNotes: ").Append(ManagerNotes).Append("\n");
            sb.Append("  MembershipStatus: ").Append(MembershipStatus).Append("\n");
            sb.Append("  IsSubscribedToAnnouncements: ").Append(IsSubscribedToAnnouncements).Append("\n");
            sb.Append("  IsSubscribedToEventAnnouncements: ").Append(IsSubscribedToEventAnnouncements).Append("\n");
            sb.Append("  Visibility: ").Append(Visibility).Append("\n");
            sb.Append("  IsRepresenting: ").Append(IsRepresenting).Append("\n");
            sb.Append("  JoinedAt: ").Append(JoinedAt).Append("\n");
            sb.Append("  BannedAt: ").Append(BannedAt).Append("\n");
            sb.Append("  Has2FA: ").Append(Has2FA).Append("\n");
            sb.Append("  HasJoinedFromPurchase: ").Append(HasJoinedFromPurchase).Append("\n");
            sb.Append("  LastPostReadAt: ").Append(LastPostReadAt).Append("\n");
            sb.Append("  MRoleIds: ").Append(MRoleIds).Append("\n");
            sb.Append("  Permissions: ").Append(Permissions).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
