/*
 * VRChat API Documentation
 *
 *
 * The version of the OpenAPI document: 1.20.6
 * Contact: vrchatapi.lpv0t@aries.fyi
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = VRChat.API.Client.FileParameter;
using OpenAPIDateConverter = VRChat.API.Client.OpenAPIDateConverter;

namespace VRChat.API.Model
{
    /// <summary>
    /// Indication of the purpose for uploading images.
    /// </summary>
    /// <value>Indication of the purpose for uploading images.</value>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum ImagePurpose
    {
        /// <summary>
        /// Enum Admin for value: admin
        /// </summary>
        [EnumMember(Value = "admin")]
        Admin = 1,

        /// <summary>
        /// Enum Avatargallery for value: avatargallery
        /// </summary>
        [EnumMember(Value = "avatargallery")]
        Avatargallery = 2,

        /// <summary>
        /// Enum Avatarimage for value: avatarimage
        /// </summary>
        [EnumMember(Value = "avatarimage")]
        Avatarimage = 3,

        /// <summary>
        /// Enum Bundle for value: bundle
        /// </summary>
        [EnumMember(Value = "bundle")]
        Bundle = 4,

        /// <summary>
        /// Enum Emoji for value: emoji
        /// </summary>
        [EnumMember(Value = "emoji")]
        Emoji = 5,

        /// <summary>
        /// Enum Emojianimated for value: emojianimated
        /// </summary>
        [EnumMember(Value = "emojianimated")]
        Emojianimated = 6,

        /// <summary>
        /// Enum Gallery for value: gallery
        /// </summary>
        [EnumMember(Value = "gallery")]
        Gallery = 7,

        /// <summary>
        /// Enum Icon for value: icon
        /// </summary>
        [EnumMember(Value = "icon")]
        Icon = 8,

        /// <summary>
        /// Enum Listinggallery for value: listinggallery
        /// </summary>
        [EnumMember(Value = "listinggallery")]
        Listinggallery = 9,

        /// <summary>
        /// Enum Product for value: product
        /// </summary>
        [EnumMember(Value = "product")]
        Product = 10,

        /// <summary>
        /// Enum Sticker for value: sticker
        /// </summary>
        [EnumMember(Value = "sticker")]
        Sticker = 11
    }

}
