/*
 * VRChat API Documentation
 *
 *
 * The version of the OpenAPI document: 2.20.7-nightly.33
 * Contact: vrchatapi.lpv0t@aries.fyi
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = VRChat.API.Client.FileParameter;
using OpenAPIDateConverter = VRChat.API.Client.OpenAPIDateConverter;

namespace VRChat.API.Model
{
    /// <summary>
    /// Defines PlayerModerationType
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum PlayerModerationType
    {
        /// <summary>
        /// Enum Block for value: block
        /// </summary>
        [EnumMember(Value = "block")]
        Block = 1,

        /// <summary>
        /// Enum HideAvatar for value: hideAvatar
        /// </summary>
        [EnumMember(Value = "hideAvatar")]
        HideAvatar = 2,

        /// <summary>
        /// Enum InteractOff for value: interactOff
        /// </summary>
        [EnumMember(Value = "interactOff")]
        InteractOff = 3,

        /// <summary>
        /// Enum InteractOn for value: interactOn
        /// </summary>
        [EnumMember(Value = "interactOn")]
        InteractOn = 4,

        /// <summary>
        /// Enum Mute for value: mute
        /// </summary>
        [EnumMember(Value = "mute")]
        Mute = 5,

        /// <summary>
        /// Enum MuteChat for value: muteChat
        /// </summary>
        [EnumMember(Value = "muteChat")]
        MuteChat = 6,

        /// <summary>
        /// Enum ShowAvatar for value: showAvatar
        /// </summary>
        [EnumMember(Value = "showAvatar")]
        ShowAvatar = 7,

        /// <summary>
        /// Enum Unmute for value: unmute
        /// </summary>
        [EnumMember(Value = "unmute")]
        Unmute = 8,

        /// <summary>
        /// Enum UnmuteChat for value: unmuteChat
        /// </summary>
        [EnumMember(Value = "unmuteChat")]
        UnmuteChat = 9
    }

}
