/*
 * VRChat API Documentation
 *
 *
 * The version of the OpenAPI document: 1.20.5
 * Contact: vrchatapi.lpv0t@aries.fyi
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = VRChat.API.Client.FileParameter;
using OpenAPIDateConverter = VRChat.API.Client.OpenAPIDateConverter;

namespace VRChat.API.Model
{
    /// <summary>
    /// UpdateGroupGalleryRequest
    /// </summary>
    [DataContract(Name = "UpdateGroupGalleryRequest")]
    public partial class UpdateGroupGalleryRequest : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="UpdateGroupGalleryRequest" /> class.
        /// </summary>
        /// <param name="name">Name of the gallery..</param>
        /// <param name="description">Description of the gallery..</param>
        /// <param name="membersOnly">Whether the gallery is members only. (default to false).</param>
        /// <param name="roleIdsToView"> .</param>
        /// <param name="roleIdsToSubmit"> .</param>
        /// <param name="roleIdsToAutoApprove"> .</param>
        /// <param name="roleIdsToManage"> .</param>
        public UpdateGroupGalleryRequest(string name = default, string description = default, bool membersOnly = false, List<string> roleIdsToView = default, List<string> roleIdsToSubmit = default, List<string> roleIdsToAutoApprove = default, List<string> roleIdsToManage = default)
        {
            this.Name = name;
            this.Description = description;
            this.MembersOnly = membersOnly;
            this.RoleIdsToView = roleIdsToView;
            this.RoleIdsToSubmit = roleIdsToSubmit;
            this.RoleIdsToAutoApprove = roleIdsToAutoApprove;
            this.RoleIdsToManage = roleIdsToManage;
        }

        /// <summary>
        /// Name of the gallery.
        /// </summary>
        /// <value>Name of the gallery.</value>
        /*
        <example>Example Gallery</example>
        */
        [DataMember(Name = "name", EmitDefaultValue = false)]
        public string Name { get; set; }

        /// <summary>
        /// Description of the gallery.
        /// </summary>
        /// <value>Description of the gallery.</value>
        /*
        <example>Example Description</example>
        */
        [DataMember(Name = "description", EmitDefaultValue = false)]
        public string Description { get; set; }

        /// <summary>
        /// Whether the gallery is members only.
        /// </summary>
        /// <value>Whether the gallery is members only.</value>
        /*
        <example>false</example>
        */
        [DataMember(Name = "membersOnly", EmitDefaultValue = true)]
        public bool MembersOnly { get; set; }

        /// <summary>
        ///  
        /// </summary>
        /// <value> </value>
        [DataMember(Name = "roleIdsToView", EmitDefaultValue = true)]
        public List<string> RoleIdsToView { get; set; }

        /// <summary>
        ///  
        /// </summary>
        /// <value> </value>
        [DataMember(Name = "roleIdsToSubmit", EmitDefaultValue = true)]
        public List<string> RoleIdsToSubmit { get; set; }

        /// <summary>
        ///  
        /// </summary>
        /// <value> </value>
        [DataMember(Name = "roleIdsToAutoApprove", EmitDefaultValue = true)]
        public List<string> RoleIdsToAutoApprove { get; set; }

        /// <summary>
        ///  
        /// </summary>
        /// <value> </value>
        [DataMember(Name = "roleIdsToManage", EmitDefaultValue = true)]
        public List<string> RoleIdsToManage { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class UpdateGroupGalleryRequest {\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  Description: ").Append(Description).Append("\n");
            sb.Append("  MembersOnly: ").Append(MembersOnly).Append("\n");
            sb.Append("  RoleIdsToView: ").Append(RoleIdsToView).Append("\n");
            sb.Append("  RoleIdsToSubmit: ").Append(RoleIdsToSubmit).Append("\n");
            sb.Append("  RoleIdsToAutoApprove: ").Append(RoleIdsToAutoApprove).Append("\n");
            sb.Append("  RoleIdsToManage: ").Append(RoleIdsToManage).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // Name (string) minLength
            if (this.Name != null && this.Name.Length < 1)
            {
                yield return new ValidationResult("Invalid value for Name, length must be greater than 1.", new [] { "Name" });
            }

            // Description (string) minLength
            if (this.Description != null && this.Description.Length < 0)
            {
                yield return new ValidationResult("Invalid value for Description, length must be greater than 0.", new [] { "Description" });
            }

            yield break;
        }
    }

}
