on:
  push:
    branches:
      - '**'
  pull_request:
  workflow_call:
    inputs:
      ref:
        description: Ref of this repository to build.
        required: false
        type: string
        default: main

name: Build

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with:
          repository: vrchatapi/vrchatapi-csharp
          ref: ${{ inputs.ref || github.ref }}

      - uses: vrchatapi/specification/.github/actions/generator@ci/modernise-actions

      - uses: vrchatapi/specification/.github/actions/bundle@ci/modernise-actions
        with:
          bundle: openapi-legacy.yaml

      - uses: actions/setup-dotnet@v6
        with:
          dotnet-version: '8.0.x'

      - run: bash ./generate.sh openapi-legacy.yaml "$(yq -r '.info.version' openapi-legacy.yaml)"

      - run: dotnet build src/VRChat.API/VRChat.API.csproj --configuration Release
